import { createContext, useContext, useState } from "react";

const am = {
  appName: "ፍዩልፍሎው", tagline: "ወረፋ አስተዳደር",
  solutions: "መፍትሄዎች", howItWorks: "እንዴት ይሰራል", benefits: "ጥቅሞች", userTypes: "የተጠቃሚ ዓይነቶች",
  login: "ግባ", signUp: "ተመዝገብ", selectLanguage: "ቋንቋ ምረጥ",
  heroSubtitle: "ለነዳጅ ጣቢያ ወረፋዎች ዘመናዊ አስተዳደር ስርዓት።",
  heroDesc: "ሾፌሮች ዲጂታል ወረፋ ይቀላቀላሉ። ጣቢያዎች የነዳጅ ፍሰት ያስተዳድራሉ።",
  step1Title: "ሾፌሮች ወረፋ ይቀላቀላሉ", step1Desc: "ጣቢያ ምረጥ እና ወዲያውኑ ወረፋ ተቀላቀል።",
  step2Title: "PIN ኮድ ያግኙ", step2Desc: "እያንዳንዱ ተጠቃሚ ለወረፋ ቦታቸው ልዩ ኮድ ያገኛሉ።",
  step3Title: "ጣቢያዎች ፍሰቱን ያስተዳድራሉ", step3Desc: "አስተዳዳሪዎች የነዳጅ ዝግጁነት ይቆጣጠራሉ።",
  overviewTitle: "ሁሉን አቀፍ የስርዓት ዳሰሳ",
  feat1Label: "የተለዩ ወረፋዎች", feat1Text: "ለቤንዚን እና ዲዝል የተለዩ አስተዳደር።",
  feat2Label: "ቀጥታ ዝማኔዎች", feat2Text: "ወዲያውኑ ማሳወቂያዎች ስለ ወረፋ እና ነዳጅ ሁኔታ።",
  feat3Label: "PIN ላይ የተመሰረተ መለያ", feat3Text: "ለእያንዳንዱ ሾፌር ደህንነቱ የተጠበቀ ዲጂታል ቶከን።",
  feat4Label: "የአስተዳዳሪ ቁጥጥሮች", feat4Text: "ለጣቢያ አስተዳዳሪዎች የላቀ ዳሽቦርድ።",
  designedTitle: "ለሁሉም የተዘጋጀ",
  forDrivers: "ለሾፌሮች", driverAccountTitle: "የሾፌር መለያ",
  driverFeature1: "ከርቀት ወረፋ ይቀላቀሉ", driverFeature2: "ቦታን በቀጥታ ይከታተሉ", driverFeature3: "ዲጂታል PIN ለማረጋገጫ",
  forStations: "ለጣቢያዎች", adminAccountTitle: "የጣቢያ አስተዳዳሪ",
  adminFeature1: "የነዳጅ ዓይነት ዝግጁነት ያስተዳድሩ", adminFeature2: "ወረፋዎችን ይቆጣጠሩ", adminFeature3: "ተጠቃሚዎችን በቅደም ተከተል ያስተናግዱ",
  whyTitle: "ለምን ፍዩልፍሎው?",
  why1Title: "ግራ መጋባትን ያስወግዱ", why1Desc: "ግልጽ ዲጂታል ክትትል ያቀርባል።",
  why2Title: "የተደራጀ ፍሰት", why2Desc: "ወረፋዎችን በነዳጅ ዓይነት ይደራጃል።",
  why3Title: "ደህንነት ቅድሚያ", why3Desc: "ጣቢያ ቅጥር ውስጥ መጨናነቅን ይከላከላል።",
  why4Title: "ሊተነበይ የሚችል ሎጂክ", why4Desc: "የጣቢያ ስራዎችን ሊተነበይ የሚችል ያደርጋል።",
  ctaTitle: "ፍዩልፍሎውን ዛሬ ይጀምሩ", ctaDesc: "ሺዎች ጣቢያዎች እና ሾፌሮች ቀድሞ ተቀላቅለዋል።",
  userDashboard: "የተጠቃሚ ዳሽቦርድ", adminDashboardLink: "የአስተዳዳሪ ዳሽቦርድ",
  footerCopy: "© 2024 ፍዩልፍሎው። መብቱ በህግ የተጠበቀ ነው።",
  privacyPolicy: "የግላዊነት ፖሊሲ", termsOfService: "የአገልግሎት ውሎች", contact: "ያግኙን", support: "ድጋፍ",
  dashboard: "ዳሽቦርድ", stations: "ጣቢያዎች", queueAdmin: "ወረፋ አስተዳዳሪ", driverHome: "ሾፌር መነሻ",
  profile: "መገለጫ", myQueue: "የኔ ወረፋ", logout: "ውጣ",
  searchPlaceholder: "ጣቢያዎችን ፈልግ...", nearMe: "ቅርብ", smartPick: "ምርጥ ምርጫ",
  allStations: "ሁሉም ጣቢያዎች", petrolOnly: "ቤንዚን ብቻ", dieselOnly: "ዲዝል ብቻ", hours24: "24 ሰዓት",
  noStations: "ምንም ጣቢያ አልተገኘም።", smartPickResult: "ምርጥ ጣቢያ", smartPickDesc: "አጭሩ የጠበቃ ጊዜ ያለው ጣቢያ ተመርጧል።",
  nearMeResult: "ቅርብ ጣቢያዎች", nearMeDesc: "ጣቢያዎቹ በርቀት ተደርድረዋል።",
  notifications: "ማሳወቂያዎች", settings: "ቅንብሮች", language: "ቋንቋ",
  noNotifications: "ምንም ማሳወቂያ የለም።", markAllRead: "ሁሉንም እንደተነበበ ምልክት አድርግ",
  queueStatus: "የወረፋ ሁኔታ", currentPosition: "አሁን ያለ ቦታ", peopleAhead: "ቀድሞ ያሉ",
  estimatedWait: "የሚጠበቅ ጊዜ", queueProgress: "የወረፋ እድገት", yourSecretCode: "ሚስጥራዊ ኮድዎ",
  scanAtPump: "በፓምፕ ላይ ቃኝ", leaveQueue: "ወረፋ ለቅ", pauseMySpot: "ቦታዬን አቁም", resumeMySpot: "ቦታዬን ቀጥል",
  adminDashboard: "የአስተዳዳሪ ዳሽቦርድ", activeSession: "ንቁ ክፍለ ጊዜዎች",
  backToHome: "ወደ መነሻ ተመለስ", saveChanges: "ለውጦችን አስቀምጥ", updateProfile: "መገለጫ አዘምን",
  pollingLive: "ቀጥታ ዝማኔ", viewStation: "ጣቢያ ይመልከቱ",
  // Admin control center
  serve: "አስተናግድ", noShow: "አልቀረበም", removeUser: "አስወግድ", serveTime: "የአገልግሎት ጊዜ",
  position: "ቦታ", eta: "የሚጠበቅ ጊዜ", pin: "ፒን", elapsed: "ያለፈ ጊዜ",
  fuelAvailable: "ነዳጅ አለ", noFuel: "ነዳጅ የለም", queueActive: "ወረፋ ንቁ", queuePaused: "ወረፋ ቆሟል",
  congestionLow: "ዝቅተኛ ጭናነት", congestionMed: "መካከለኛ ጭናነት", congestionHigh: "ከፍተኛ ጭናነት",
  liveQueue: "ቀጥታ ወረፋ", stationControl: "የጣቢያ ቁጥጥር", analyticsTitle: "ትንታኔ",
  alertsTitle: "ማስጠንቀቂያዎች", efficiency: "ብቃት", peakHour: "ከፍተኛ ሰዓት",
  totalServed: "ጠቅላላ ያስተናገደ", totalJoins: "ጠቅላላ የተቀላቀለ", avgWait: "አማካይ ጠበቃ",
  vehiclesInQueue: "ተሽከርካሪዎች በወረፋ", adjustServeTime: "የአገልግሎት ጊዜ አስተካክል",
  confirmServe: "ለማስተናገድ ያረጋግጡ", confirmNoShow: "ለ'አልቀረበም' ያረጋግጡ",
  wsConnected: "ቀጥታ ግንኙነት", wsDisconnected: "ግንኙነት ተቋርጧል",
  // Reservation
  reserveSlot: "ጊዜ ቦታ ያስይዙ", myReservations: "የኔ ቦታዎች", cancelReservation: "ቦታ ሰርዝ",
  slotFull: "ሞልቷል", slotsLeft: "ቦታ ቀርቷል", confirmReservation: "ቦታ አረጋግጥ",
  // Map
  mapView: "የካርታ እይታ", liveMap: "ቀጥታ ካርታ",
  // AI
  aiInsights: "AI ትንታኔ", shortageRisk: "የነዳጅ እጥረት ስጋት", demandForecast: "የፍላጎት ትንበያ",
  travelSuggestions: "የጉዞ ምክሮች", fuelEstimator: "የነዳጅ ግምት",
};

const en = {
  appName: "FuelFlow", tagline: "Queue Management & Dispatch Portal",
  solutions: "Solutions", howItWorks: "How it Works", benefits: "Benefits", userTypes: "User Types",
  login: "Login", signUp: "Sign Up", selectLanguage: "Select Language",
  heroSubtitle: "A smart system for managing fuel station queues in real time.",
  heroDesc: "Drivers join fuel queues digitally. Stations manage fuel flow and waiting lists efficiently.",
  step1Title: "Drivers join queue", step1Desc: "Select a station and join a fuel queue instantly.",
  step2Title: "Get a PIN code", step2Desc: "Each user receives a unique code for their queue position.",
  step3Title: "Stations manage flow", step3Desc: "Admins control fuel availability and serve users in order.",
  overviewTitle: "Comprehensive System Overview",
  feat1Label: "Separate Queues", feat1Text: "Dedicated management for Petrol and Diesel fuel types to avoid congestion.",
  feat2Label: "Real-Time Updates", feat2Text: "Instant notifications on queue progress and station fuel status.",
  feat3Label: "PIN-Based Identification", feat3Text: "Secure digital tokens for every driver to ensure order integrity.",
  feat4Label: "Admin Controls", feat4Text: "Advanced dashboard for station managers to regulate the flow.",
  designedTitle: "Designed for Everyone",
  forDrivers: "For Drivers", driverAccountTitle: "Driver Account",
  driverFeature1: "Join queues remotely", driverFeature2: "Track position in real-time", driverFeature3: "Digital PIN for verification",
  forStations: "For Stations", adminAccountTitle: "Station Admin",
  adminFeature1: "Manage fuel type availability", adminFeature2: "Control queues & waiting lists", adminFeature3: "Serve users in digital order",
  whyTitle: "Why FuelFlow?",
  why1Title: "Eliminate Confusion", why1Desc: "Reduces waiting confusion with clear digital tracking.",
  why2Title: "Organized Flow", why2Desc: "Organizes fuel queues separately per fuel type.",
  why3Title: "Safety First", why3Desc: "Prevents overcrowding at the station premises.",
  why4Title: "Predictable Logic", why4Desc: "Makes station operations predictable and efficient.",
  ctaTitle: "Start using FuelFlow today", ctaDesc: "Join thousands of stations and drivers already streamlining their fueling experience.",
  userDashboard: "User Dashboard", adminDashboardLink: "Admin Dashboard",
  footerCopy: "© 2024 FuelFlow Fuel Management. All rights reserved.",
  privacyPolicy: "Privacy Policy", termsOfService: "Terms of Service", contact: "Contact", support: "Support",
  dashboard: "Dashboard", stations: "Stations", queueAdmin: "Queue Admin", driverHome: "Driver Home",
  profile: "Profile", myQueue: "My Queue", logout: "Logout",
  searchPlaceholder: "Search for stations near you...", nearMe: "Near Me", smartPick: "Smart Pick",
  allStations: "All Stations", petrolOnly: "Petrol Only", dieselOnly: "Diesel Only", hours24: "24 Hours",
  noStations: "No stations match your search.", smartPickResult: "Best Station", smartPickDesc: "Picked the station with the shortest available wait time.",
  nearMeResult: "Nearest Stations", nearMeDesc: "Stations sorted by distance.",
  notifications: "Notifications", settings: "Settings", language: "Language",
  noNotifications: "No notifications yet.", markAllRead: "Mark all as read",
  queueStatus: "Queue Status", currentPosition: "Current Position", peopleAhead: "People Ahead",
  estimatedWait: "Estimated Wait", queueProgress: "Queue Progress", yourSecretCode: "Your Secret Code",
  scanAtPump: "Scan at Pump", leaveQueue: "Leave Queue", pauseMySpot: "Pause My Spot", resumeMySpot: "Resume My Spot",
  adminDashboard: "Admin Dashboard", activeSession: "Current Active Sessions",
  backToHome: "Back to Home", saveChanges: "Save Changes", updateProfile: "Update Profile",
  pollingLive: "Live Updates", viewStation: "View Station",
  // Admin control center
  serve: "Serve", noShow: "No Show", removeUser: "Remove", serveTime: "Serve Time",
  position: "Position", eta: "ETA", pin: "PIN", elapsed: "Elapsed",
  fuelAvailable: "Fuel Available", noFuel: "No Fuel", queueActive: "Queue Active", queuePaused: "Queue Paused",
  congestionLow: "Low Congestion", congestionMed: "Medium Congestion", congestionHigh: "High Congestion",
  liveQueue: "Live Queue", stationControl: "Station Control", analyticsTitle: "Analytics",
  alertsTitle: "Alerts", efficiency: "Efficiency", peakHour: "Peak Hour",
  totalServed: "Total Served", totalJoins: "Total Joins", avgWait: "Avg Wait",
  vehiclesInQueue: "Vehicles in Queue", adjustServeTime: "Adjust Serve Time",
  confirmServe: "Confirm serve this driver?", confirmNoShow: "Mark as no-show?",
  wsConnected: "Live Connected", wsDisconnected: "Disconnected",
  // Reservation
  reserveSlot: "Reserve a Slot", myReservations: "My Reservations", cancelReservation: "Cancel",
  slotFull: "Full", slotsLeft: "left", confirmReservation: "Confirm Reservation",
  // Map
  mapView: "Map View", liveMap: "Live Station Map",
  // AI
  aiInsights: "AI Insights", shortageRisk: "Shortage Risk", demandForecast: "Demand Forecast",
  travelSuggestions: "Travel Suggestions", fuelEstimator: "Fuel Estimator",
};

const om = {
  appName: "FuelFlow", tagline: "Bulchiinsa Tarree",
  solutions: "Furmaata", howItWorks: "Akkamitti Hojjeta", benefits: "Faayidaa", userTypes: "Gosa Fayyadamaa",
  login: "Seeni", signUp: "Galmaai", selectLanguage: "Afaan Filadhu",
  heroSubtitle: "Sirna ammayyaa bulchiinsa tarree teessoo dhaabbata bobaa.",
  heroDesc: "Konkolaattonni tarree dijitaalaa ni makamu. Teessoon yaaa bobaa ni bulcha.",
  step1Title: "Konkolaattonni tarree makamu", step1Desc: "Teessoo filadhu tarreetti makamu.",
  step2Title: "Koodii PIN argadhu", step2Desc: "Fayyadamaan hunduu koodii addaa argata.",
  step3Title: "Teessoon yaaa ni bulcha", step3Desc: "Bulchaan argamummaa bobaa ni toata.",
  overviewTitle: "Cuunfaa Sirna Guutuu",
  feat1Label: "Tarreewwan Addaa", feat1Text: "Bulchiinsa addaa Beenziinaa fi Diizilaa.",
  feat2Label: "Haaromsa Kallattii", feat2Text: "Beeksisa hatattamaa tarree fi haala bobaa.",
  feat3Label: "Eenyummaa PIN", feat3Text: "Tokeenii dijitaalaa nageenya qabu.",
  feat4Label: "Toannoo Bulchaa", feat4Text: "Gabatee olaanaa bulchaa teessoo.",
  designedTitle: "Hundaaf Qophaae",
  forDrivers: "Konkolaattoota", driverAccountTitle: "Herrega Konkolaataa",
  driverFeature1: "Fageenya irraa tarree makamu", driverFeature2: "Bakka kallattiin hordofu", driverFeature3: "PIN dijitaalaa mirkaneessuu",
  forStations: "Teessoo", adminAccountTitle: "Bulchaa Teessoo",
  adminFeature1: "Argamummaa bobaa bulchuu", adminFeature2: "Tarreewwan toachuu", adminFeature3: "Fayyadamtoota tarreessaan tajaajiluu",
  whyTitle: "Maaliif FuelFlow?",
  why1Title: "Walxaxaa Haquu", why1Desc: "Hordoffii dijitaalaa ifa taeen.",
  why2Title: "Yaaa Qindaae", why2Desc: "Tarreewwan bobaa gosa irratti.",
  why3Title: "Nageenya Dursa", why3Desc: "Teessoo keessatti cufamuu ni dhorka.",
  why4Title: "Loojikii Tilmaamamuuf", why4Desc: "Hojii teessoo tilmaamamuuf ni taasisa.",
  ctaTitle: "FuelFlow haraa jalqabi", ctaDesc: "Kumaatamni teessoo fi konkolaattonni duraan makamaniiru.",
  userDashboard: "Gabatee Fayyadamaa", adminDashboardLink: "Gabatee Bulchaa",
  footerCopy: "© 2024 FuelFlow. Mirgi seeraan eegame.",
  privacyPolicy: "Imaammata Dhuunfaa", termsOfService: "Hayyama Tajaajilaa", contact: "Nu Quunnamaa", support: "Deeggarsa",
  dashboard: "Gabatee", stations: "Teessoo", queueAdmin: "Bulchaa Tarree", driverHome: "Mana Konkolaachisaa",
  profile: "Profaayilii", myQueue: "Tarree Koo", logout: "Bai",
  searchPlaceholder: "Teessoo barbaaduuf...", nearMe: "Naan Koo", smartPick: "Filannoo Caalaa",
  allStations: "Teessoo Hunda", petrolOnly: "Beenziina Qofa", dieselOnly: "Diizila Qofa", hours24: "Saa 24",
  noStations: "Teessoon hin argamne.", smartPickResult: "Teessoo Filatame", smartPickDesc: "Teessoon yeroo eeggannaa gabaabaa qabu filatame.",
  nearMeResult: "Teessoo Dhiyoo", nearMeDesc: "Teessoon fageenya irratti tarreeffame.",
  notifications: "Beeksisa", settings: "Qindaaina", language: "Afaan",
  noNotifications: "Beeksisni hin jiru.", markAllRead: "Hunda dubbifame godhuu",
  queueStatus: "Haala Tarree", currentPosition: "Bakka Ammaa", peopleAhead: "Duratti Jiran",
  estimatedWait: "Yeroo Eeggannaa", queueProgress: "Tarree Guddina", yourSecretCode: "Koodii Dhokataa Kee",
  scanAtPump: "Paampii Irratti Sakattai", leaveQueue: "Tarree Dhiisi", pauseMySpot: "Bakka Koo Dhaabi", resumeMySpot: "Bakka Koo Itti Fufi",
  adminDashboard: "Gabatee Bulchaa", activeSession: "Waltajjii Hojii Jiran",
  backToHome: "Gara Manaatti Deebi", saveChanges: "Jijjiirama Kuusi", updateProfile: "Profaayilii Haaromsi",
  pollingLive: "Haaromsa Kallattii", viewStation: "Teessoo Ilaali",
  serve: "Tajaajili", noShow: "Hin Dhiyanne", removeUser: "Haquu", serveTime: "Yeroo Tajaajilaa",
  position: "Bakka", eta: "Yeroo Eeggannaa", pin: "PIN", elapsed: "Yeroo Darbe",
  fuelAvailable: "Bobaa Jira", noFuel: "Bobaa Hin Jiru", queueActive: "Tarree Hojjechaa", queuePaused: "Tarree Dhaabatee",
  congestionLow: "Cufamuu Gadi", congestionMed: "Cufamuu Giddugaleessa", congestionHigh: "Cufamuu Olaanaa",
  liveQueue: "Tarree Kallattii", stationControl: "Toannoo Teessoo", analyticsTitle: "Xiinxala",
  alertsTitle: "Beeksisota", efficiency: "Danda'ama", peakHour: "Yeroo Olaanaa",
  totalServed: "Waliigala Tajaajilame", totalJoins: "Waliigala Makame", avgWait: "Giddugaleessa Eeggannaa",
  vehiclesInQueue: "Konkolaatota Tarreetti", adjustServeTime: "Yeroo Tajaajilaa Sirreessi",
  confirmServe: "Tajaajiluu mirkaneessi?", confirmNoShow: "Hin dhiyanne godhuu?",
  wsConnected: "Kallattiin Walqabatame", wsDisconnected: "Walqabatamuu Cufame",
  reserveSlot: "Yeroo Qabadhu", myReservations: "Qabannoo Koo", cancelReservation: "Haquu",
  slotFull: "Guutee", slotsLeft: "hafe", confirmReservation: "Qabannoo Mirkaneessi",
  mapView: "Kaartaa Ilaali", liveMap: "Kaartaa Kallattii",
  aiInsights: "AI Xiinxala", shortageRisk: "Sodaa Dhabuu", demandForecast: "Tilmaama Fedhii",
  travelSuggestions: "Gorsa Imala", fuelEstimator: "Tilmaama Bobaa",
};

const ti = {
  appName: "FuelFlow", tagline: "Akayadi Werefa Portal",
  solutions: "Meftihitat", howItWorks: "Kemey Yiserh", benefits: "Rebhitat", userTypes: "Aynet Teqeqemti",
  login: "Eto", signUp: "Temezgeb", selectLanguage: "Qwanqwa Merets",
  heroSubtitle: "Zemenawy srat mhdera werefa tabiya nedadi.",
  heroDesc: "Shuferatat dijitalawi werefa yiqelaqelu. Tabitatat nay nedadi fset yekaidu.",
  step1Title: "Shuferatat werefa yiqelaqelu", step1Desc: "Tabiya merets wediyawnu werefa teqelaqel.",
  step2Title: "PIN kod rkheb", step2Desc: "Nefsi wekef teqeqami nay werefa bota kod yiwehabo.",
  step3Title: "Tabitatat fset yekaidu", step3Desc: "Akayadi nay nedadi mhllaw yiqotsatseru.",
  overviewTitle: "Hafeshawi nay srat dasesa",
  feat1Label: "Felali Werefatat", feat1Text: "Nay benzin n dizl fluy mhdera.",
  feat2Label: "Qetita Zmatenet", feat2Text: "Wediyawnu mlktat nay werefa n nedadi kunetat.",
  feat3Label: "PIN ztemorkese melelyi", feat3Text: "Nay dhnet dijitalawi token nnefsi wekef shufer.",
  feat4Label: "Nay Akayadi Qutsatser", feat4Text: "Zleale dashboard nakayadi tabiya.",
  designedTitle: "Nkulu ztedalwe",
  forDrivers: "Nshuferatat", driverAccountTitle: "Nay shufer hsab",
  driverFeature1: "Kab rhuts werefa meqlaql", driverFeature2: "Bota qetita mktatal", driverFeature3: "Dijitalawi PIN nmrggats",
  forStations: "Ntabitatat", adminAccountTitle: "Akayadi Tabiya",
  adminFeature1: "Mhllaw nedadi mhdera", adminFeature2: "Werefatat mqutsatser", adminFeature3: "Teqeqemti bqedem msaeb msnae",
  whyTitle: "Slemntay FuelFlow?",
  why1Title: "Mdngar mwgad", why1Desc: "Bdijitalawi kttl mdngar mqnas.",
  why2Title: "Ztewedebbe Fset", why2Desc: "Werefatat baynet nedadi mmqal.",
  why3Title: "Dhnet Qdmi Kulu", why3Desc: "Mtsqat ab tabiya mklkal.",
  why4Title: "Litebeyo Zkhel Lojik", why4Desc: "Srhat tabiya litebeyo zkhel mgbar.",
  ctaTitle: "FuelFlow lomi jemer", ctaDesc: "Ashhat tabitatat n shuferatat qedimomu teqelaqilomu.",
  userDashboard: "Dashboard Teqeqami", adminDashboardLink: "Dashboard Akayadi",
  footerCopy: "© 2024 FuelFlow. Kulu meselat tehazilu.",
  privacyPolicy: "Polisi Mstirawnet", termsOfService: "Wetli Agelglot", contact: "Rkhebuna", support: "Degef",
  dashboard: "Dashboard", stations: "Tabitatat", queueAdmin: "Akayadi Werefa", driverHome: "Mebegesi Shufer",
  profile: "Profile", myQueue: "Werefay", logout: "Wtsae",
  searchPlaceholder: "Tabitatat dle...", nearMe: "Qereba", smartPick: "Blhategna Mrha",
  allStations: "Kulom Tabitatat", petrolOnly: "Benzin Tray", dieselOnly: "Dizl Tray", hours24: "24 Seat",
  noStations: "Zkhone tabiya ayterkheben.", smartPickResult: "Zbelese Tabiya", smartPickDesc: "Tabiya zhatsere nay mtsbayi gze zelowo temeritu.",
  nearMeResult: "Qereba Tabitatat", nearMeDesc: "Tabitatat brhqet tserieu.",
  notifications: "Mlktat", settings: "Qnbrat", language: "Qwanqwa",
  noNotifications: "Mlktat yelen.", markAllRead: "Kulu kem ztenbbe mlkt gber",
  queueStatus: "Kunetat Werefa", currentPosition: "Hji zelo Bota", peopleAhead: "Qdmikha zelew",
  estimatedWait: "Gmtawi nay mtsbayi gze", queueProgress: "Mebale Werefa", yourSecretCode: "Mstirawi Kodka",
  scanAtPump: "Ab Pamp Qani", leaveQueue: "Werefa Hadg", pauseMySpot: "Botay Aqarts", resumeMySpot: "Botay Qetsl",
  adminDashboard: "Dashboard Akayadi", activeSession: "Hji zelew kfle-gzetatat",
  backToHome: "Nab Mebegesi Temelese", saveChanges: "Lewttat Aqeb", updateProfile: "Profile Azemn",
  pollingLive: "Qetita Zmate", viewStation: "Tabiya Rae",
  serve: "Saeb", noShow: "Ayteqereb", removeUser: "Aqli", serveTime: "Gze Msaeb",
  position: "Bota", eta: "Gmtawi Gze", pin: "PIN", elapsed: "Zhalefe Gze",
  fuelAvailable: "Nedadi Alo", noFuel: "Nedadi Yelen", queueActive: "Werefa Hiji", queuePaused: "Werefa Teqimu",
  congestionLow: "Tsqat Tsigu", congestionMed: "Mekakelegna Tsigu", congestionHigh: "Zleale Tsigu",
  liveQueue: "Qetita Werefa", stationControl: "Qutsatser Tabiya", analyticsTitle: "Analitics",
  alertsTitle: "Mlktat", efficiency: "Btsanet", peakHour: "Zleale Gze",
  totalServed: "Wuqur Zteseabe", totalJoins: "Wuqur Zteqelaqele", avgWait: "Mekakelegna Mtsbayi",
  vehiclesInQueue: "Meknatat Bwerefa", adjustServeTime: "Gze Msaeb Asarih",
  confirmServe: "Msaeb mrkgats?", confirmNoShow: "Ayteqereb godhuu?",
  wsConnected: "Qetita Teqeqime", wsDisconnected: "Teqeqim Teqimu",
  reserveSlot: "Gze Qebets", myReservations: "Qebetsatey", cancelReservation: "Aqli",
  slotFull: "Temilu", slotsLeft: "tehazilu", confirmReservation: "Qebets Mrkgats",
  mapView: "Mapa Rae", liveMap: "Qetita Mapa",
  aiInsights: "AI Analitics", shortageRisk: "Sodaa Dhabuu", demandForecast: "Tilmaama Fedhii",
  travelSuggestions: "Gorsa Imala", fuelEstimator: "Tilmaama Nedadi",
};

export const LANGUAGES = {
  am: { code: "am", name: "አማርኛ", label: "Amharic", t: am },
  en: { code: "en", name: "English", label: "English", t: en },
  om: { code: "om", name: "Afaan Oromoo", label: "Oromia", t: om },
  ti: { code: "ti", name: "Tigrinya", label: "Tigray", t: ti },
};

const LanguageContext = createContext(null);

const STORAGE_KEY = 'ff_lang';

export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored && LANGUAGES[stored] ? stored : 'am';
  });

  const setLang = (code) => {
    if (!LANGUAGES[code]) return;
    localStorage.setItem(STORAGE_KEY, code);
    setLangState(code);
  };

  const value = { lang, setLang, t: LANGUAGES[lang].t, languages: LANGUAGES };
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLang = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be used inside LanguageProvider");
  return ctx;
};
